---
title: "The relationship between restaurant geographical distribution and chronic disease outcomes in New York City"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
library(readxl)
library(data.table)
library(stringr)
library(janitor)
library(stringr)
library(forcats)
library(jsonlite)
library(viridis)
library(plotly)
library(ggplot2)
library(knitr)
```

```{r New_York_Inspection_data, include=FALSE}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

rest_inspection = get_all_inspections(url) %>%
  bind_rows() 
```

```{r health_data, include=FALSE}
download.file("https://www1.nyc.gov/assets/doh/downloads/excel/episrv/2015_CHP_PUD.xlsx", mode="wb", destfile = "health.xlsx")
health <- read_excel("health.xlsx", sheet = "CHP_all_data") %>% 
  select(Name, Racewhite_Rate, Poverty, Unemployment,
         Smoking, Exercise,
         Obesity, Diabetes, Stroke_Hosp) %>% 
  clean_names() 
```

```{r neighborhood_restaurant, include=FALSE}
zip_neighbor <- read_csv("neigh_zipcode.csv") %>% 
  mutate(zipcode = as.character(zipcode))
##restaurant data with neighbourhood
rest_neighborhood = left_join(rest_inspection, zip_neighbor, by = "zipcode") %>% 
  filter(!is.na(neighborhood))
```


Column {data-width=500}
-----------------------------------------------------------------------

### Health Data

```{r neighborhood_health}
health_outcome <- health[-c(1:6),] %>% 
  rename(neighborhood = name) %>% 
  mutate(neighborhood = as.factor(neighborhood)) %>% 
  select(neighborhood,obesity,diabetes,stroke_hosp) %>% 
  gather(key = outcomes, value = rate, obesity:stroke_hosp) 

##Plotting box plot for neighborhood outcomes 
boxplot_ob_dia <- health_outcome %>% 
  rename(percentage = rate) %>% 
  filter(outcomes == c("obesity","diabetes")) %>% 
  ggplot(aes(x = outcomes, y = percentage)) + geom_boxplot() + 
  geom_point(aes(color = neighborhood)) + theme(legend.position = "none") +
  labs(title = "Percentage of diabetes and obesity")

plotly_ob_dia <- ggplotly(boxplot_ob_dia)

boxplot_stroke <- health_outcome %>% 
  filter(outcomes == "stroke_hosp") %>% 
  ggplot(aes(x = outcomes, y = rate)) + geom_boxplot() + 
  geom_point(aes(color = neighborhood)) + theme(legend.position = "none") +
  labs(title = "Obesity and diabetes percentage    
       Rate of hospitalizations per 100,000 adults")

plotly_stroke <- ggplotly(boxplot_stroke)

subplot(hide_legend(plotly_ob_dia),hide_legend(plotly_stroke))
```

### Number of fastfood and non-fastfood restaurants in each neighborhood

```{r calculating_percentage}
neighborhood_list = 
  rest_neighborhood %>%
  distinct(neighborhood) %>%
  arrange(neighborhood)
  
rest_fastfood_neighborhood = 
  rest_neighborhood %>%
  filter(cuisine_description %in% c("Bagels/Pretzels",
                                    "Bottled beverages, including water, sodas, juices, etc.",
                                    "Chicken",
                                    "Delicatessen",
                                    "Donuts",
                                    "Hamburgers",
                                    "Hotdogs",
                                    "Hotdogs/Pretzels",
                                    "Ice Cream, Gelato, Yogurt, Ices",
                                    "Nuts/Confectionary",
                                    "Pancakes/Waffles",
                                    "Pizza",
                                    "Soul Food",
                                    "Sandwiches",
                                    "Sandwiches/Salads/Mixed Buffet",
                                    "Soups & Sandwiches"))

percent_fastfood_neighborhood = function(name_neighborhood){

  rest_each_neighborhood =
    rest_neighborhood %>%
    filter(neighborhood == name_neighborhood) %>%
    distinct(camis)
  
  n_rest_neighborhood = nrow(rest_each_neighborhood)

  rest_fastfood_distinct_neighborhood = 
    rest_fastfood_neighborhood %>%
    filter(neighborhood == name_neighborhood) %>%
    distinct(camis, cuisine_description)
  
  n_fastfood_neighborhood = nrow(rest_fastfood_distinct_neighborhood)
    
  percent_fastfood_neighborhood = n_fastfood_neighborhood/n_rest_neighborhood
  
  tibble(
    neighborhood = name_neighborhood,
    n_fastfood = n_fastfood_neighborhood,
    n_rest = n_rest_neighborhood,
    percent_fastfood = percent_fastfood_neighborhood
  )
}

neighborhood_boro = 
  rest_neighborhood %>%
  distinct(neighborhood, boro) %>%
  arrange(neighborhood) %>%
  mutate(neighborhood = str_to_upper(neighborhood)) %>%
  filter(!(neighborhood == "LONG ISLAND CITY AND ASTORIA" & boro == "MANHATTAN"))

fastfood_neighborhood = 
  map(neighborhood_list$neighborhood, percent_fastfood_neighborhood) %>%
  bind_rows() %>%
  mutate(neighborhood = str_to_upper(neighborhood)) %>%
  left_join(., neighborhood_boro, by = "neighborhood")
  
# plot for each neighborhood
fastfood_neighborhood %>%
  mutate(neighborhood = as.factor(neighborhood),
         n_rest = as.numeric(n_rest),
         n_nonfastfood = n_rest - n_fastfood,
         neighborhood = fct_reorder(neighborhood, percent_fastfood),
         text_label = str_c("Neighborhood: ", neighborhood, '\nPercentage: ', format(percent_fastfood * 100, digits = 3), "%")) %>%
  plot_ly(., x = ~neighborhood, y = ~n_fastfood, type = 'bar', name = 'fastfood restaurants', text = ~text_label) %>%
  add_trace(y = ~n_nonfastfood, name = 'non-fastfood restaurants') %>%
  layout(title = "Neighborhoods ordered by percentage of fastfood restaurants",
         yaxis = list(title = 'Number of restaurants'), 
         xaxis = list(title = 'NYC Neighborhood',
                      showticklabels = FALSE),
         barmode = 'stack')
```

Column {data-width=500}
-----------------------------------------------------------------------

### Scatterplot between the three chronic disease outcomes and percentage of fastfood restaurants 

```{r getting_data_ready_for_analysis, include = FALSE}
health_neighborhood = 
  health %>%
  mutate(neighborhood = str_to_upper(name)) %>%
  select(-name)

combined_fastfood = 
  fastfood_neighborhood %>%
  mutate(fastfood_percent = percent_fastfood) %>%
  select(neighborhood, fastfood_percent)

combined_model =  
  left_join(combined_fastfood, health_neighborhood, by = "neighborhood")
```


```{r, include = FALSE}
library(broom)
combined_model_percent <- combined_model %>%  mutate(obesity_percent = obesity/100,
                                                     diabetes_percent = diabetes/100,
                                                     stroke_hosp_percent = stroke_hosp/100)
```

### Obesity_percent and fastfood_percent
```{r}
m <- lm(obesity_percent ~ fastfood_percent, data = combined_model_percent)
plot1 <- broom::augment(m) %>% 
  plot_ly(x = ~fastfood_percent) %>%
  add_markers(y = ~obesity_percent , color = I("red"), showlegend = FALSE) %>%
  add_ribbons(ymin = ~.fitted - 1.96 * .se.fit, 
              ymax = ~.fitted + 1.96 * .se.fit, color = I("gray80"),
              name = "95% confidence") %>%
  add_lines(y = ~.fitted, color = I("steelblue"), name = "obesity_percent")
plot1
```

### Diabetes_percent and fastfood_percent
```{r}
n <- lm(diabetes_percent ~ fastfood_percent, data = combined_model_percent)
plot2 <- broom::augment(n) %>% 
  plot_ly(x = ~fastfood_percent) %>%
  add_markers(y = ~diabetes_percent, color = I("yellow"), showlegend = FALSE) %>%
  add_ribbons(ymin = ~.fitted - 1.96 * .se.fit, 
              ymax = ~.fitted + 1.96 * .se.fit, color = I("gray80"),
              name = "95% confidence") %>%
  add_lines(y = ~.fitted, color = I("steelblue"),name = "diabetes_percent")
plot2
```

### Stroke_hosp_percent and fastfood_percent
```{r}
o <- lm(stroke_hosp_percent ~ fastfood_percent, data = combined_model_percent)
plot3 <- broom::augment(o) %>% 
  plot_ly(x = ~fastfood_percent) %>%
  add_markers(y = ~stroke_hosp_percent, color = I("blue"), showlegend = FALSE) %>%
  add_ribbons(ymin = ~.fitted - 1.96 * .se.fit, 
              ymax = ~.fitted + 1.96 * .se.fit, color = I("gray80"),
              name = "95% confidence") %>%
  add_lines(y = ~.fitted, color = I("steelblue"),name = "stroke_hosp_percent")
plot3
```



